In [198]:
import numpy as np

In [199]:
#Q1  Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.

In [200]:
def func1():
    n1 = np.array([1,7,13,105])
    print(f"size : {n1.nbytes}")

func1()

size : 32


In [201]:
#Q2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [202]:
def func2():
    n2 = np.array([11,43,56,78])
    n3 = np.array([2,45,90,17])
    print(n2)
    print(n3)
    print(f"Greater than")
    n4=n2>n3
    print(n4)
    print(f"Greater equl")
    n4=(n2>=n3)
    print(n4)
    print(f"Less than")
    n4= n2<n3
    print(n4)
    print(f"Less equal")
    n4= (n2<=n3)
    print(n4)

func2()

[11 43 56 78]
[ 2 45 90 17]
Greater than
[ True False False  True]
Greater equl
[ True False False  True]
Less than
[False  True  True False]
Less equal
[False  True  True False]


In [203]:
#Q3 Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [204]:
def func3():
    arr1 = np.zeros(10)
    print(arr1)
    arr2 = np.ones(10)
    print(arr2)
    arr3 = (np.ones(10)*5)
    print(arr3)
    arr4 = (np.ones(10)*10)
    print(arr4)
    arr5 = (np.ones(10)*20)
    print(arr5)
    arr6 = (np.ones(10)*50)
    print(arr6)

func3()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [205]:
#Q4 Write a NumPy program to create an array of integers from 30 to 70.

In [206]:
def func4():
    arr1 = np.arange(30,71)
    print(arr1)

func4()

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [207]:
#Q5. Write a NumPy program to create an array of integers from 50 to 95.

In [208]:
def func5():
    arr1 = np.arange(50,96)
    print(arr1)

func5()

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [209]:
#Q6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [210]:
def func6():
    arr1 = np.arange(20,80,2)
    print(arr1)

func6()

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [211]:
#Q7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [212]:
def func7():
    arr1 = np.arange(20+1,80,2)
    print(arr1)

func7()

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [213]:
#Q8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40

In [214]:
def func8():
    arr1= np.random.randint(10,40,15)
    print(arr1)

func8()

[25 36 21 19 36 29 31 23 15 23 23 27 21 14 17]


In [215]:
#Q9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [216]:
def func9():
    arr1 = np.random.randint(30,50,10)
    print(arr1)

func9()

[35 49 38 48 42 48 43 45 45 46]


In [217]:
#Q10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [218]:
def func10():
    arr1 = np.random.randint(50,90,20)
    print(arr1)

func10()

[87 89 69 64 82 65 69 63 65 52 76 65 57 78 79 70 67 59 88 66]


In [219]:
#Q11. Create any two arrays & perform various mathematical operations.    i.e. Addition, Substraction, Multiplication, Divide.

In [220]:
def func11():
    arr1 = np.array([2,5,13,55,9])
    arr2 = np.array([5,10,18,44,39])
    print(arr1+arr2)
    print(arr1-arr2)
    print(arr1*arr2)
    print(arr1/arr2)

func11()

[ 7 15 31 99 48]
[ -3  -5  -5  11 -30]
[  10   50  234 2420  351]
[0.4        0.5        0.72222222 1.25       0.23076923]


In [221]:
#Q12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [222]:
def func12():
    arr1 = np.random.randint(10,21,12)
    arr1 = arr1.reshape([3,4])
    print(arr1)

func12()

[[12 11 12 13]
 [10 20 15 17]
 [18 20 13 16]]


In [223]:
#Q13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [224]:
def func13():
    arr1 = np.eye(3)
    print(arr1)

func13()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [225]:
#Q14. Write a NumPy program to find the number of rows and columns in a given     matrix. 

In [226]:
def func14():
    arr1 = np.diag([1,2,3,4,5])
    print({arr1.shape})

func14()

{(5, 5)}


In [227]:
#Q15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [228]:
def func15():
    arr1 = np.diag([1,2,3,4,5])
    print(arr1)

func15()

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [229]:
#Q16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [230]:
def func16():
    arr1= np.random.random([3,3,3])
    print(arr1)

func16()

[[[0.15595298 0.22858829 0.99986264]
  [0.86390414 0.34457137 0.34875444]
  [0.08330523 0.55609491 0.98226461]]

 [[0.89203718 0.32185962 0.38290539]
  [0.70143998 0.94400774 0.93069024]
  [0.1229474  0.8400374  0.22782938]]

 [[0.88702588 0.9058683  0.18392537]
  [0.28027416 0.35502255 0.02034087]
  [0.62106948 0.41919321 0.19292767]]]


In [231]:
#Q17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

In [232]:
def func17():
    arr2 = np.random.random([2,3,4])
    print(arr2)

func17()

[[[0.55454372 0.45705809 0.793724   0.40673961]
  [0.14023474 0.69456601 0.61730098 0.14072198]
  [0.1660652  0.05230663 0.74614215 0.74567489]]

 [[0.65532199 0.58274607 0.01082913 0.60205306]
  [0.49339484 0.62701973 0.63778509 0.63680409]
  [0.67998944 0.66616096 0.08292218 0.46648561]]]


In [233]:
#Q18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [234]:
def func18():
    arr2 = [1,2,3,4,5,6]
    arr2 = np.array(arr2)
    print(arr2)

func18()

[1 2 3 4 5 6]


In [235]:
#Q19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [236]:
def func19():
    arr2 = np.arange(2,11)
    arr2 = arr2.reshape([3,3])
    print(arr2)

func19()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [237]:
#Q20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [238]:
def func20():
    arr2= np.arange(12,39)
    print(arr2)

func20()

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [239]:
#Q21. Write a NumPy program to reverse an array (the first element becomes the last).

In [240]:
def func21():
    arr2 = np.arange(10,20)
    print(arr2)
    arr2 = arr2[::-1]
    print(f"Reverse : {arr2}")

func21()

[10 11 12 13 14 15 16 17 18 19]
Reverse : [19 18 17 16 15 14 13 12 11 10]


In [241]:
#Q22. Write a NumPy program to convert an data type into to a floating type.

In [242]:
def func22():
    arr2 = [1,2,3,4,5]
    arr2 = np.asfarray(arr2)
    print(f"float : {arr2}")

func22()

float : [1. 2. 3. 4. 5.]


In [243]:
#Q23. Write a NumPy program to convert a list array.

In [244]:
def func23():
    arr2 = [1,2,3,4,5,6]
    arr2 = np.asarray(arr2)
    print(f"array: {arr2}")

func23()

array: [1 2 3 4 5 6]


In [245]:
#Q24. Write a NumPy program to get the element-wise remainder of an array of division.

In [246]:
def func24():
    arr2 = np.random.randint(1,80,4)
    arr3 = np.random.randint(32,90,4)
    print(arr2%arr3)

func24()

[ 4 44 12 12]


In [247]:
#Q25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [248]:
def func25():
    arr2 = np.arange(20,50)
    print(arr2%3)

func25()

[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
